name: se2_tigersafe
description: "A Campus Emergency Response Application Project"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  google_sign_in: ^6.2.2
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  sign_in_button: ^3.0.0
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/UST_LOGO_NO_TEXT.png
    - assets/UST_LOGO_WITH_TEXT.png
    - assets/UST_LOGO_NO_TEXT_300.png
    - assets/UST_LOGO_WITH_TEXT_300.png

