name: se2_tigersafe
description: "A Campus Emergency Response Application Project"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  google_sign_in: ^6.2.2
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  sign_in_button: ^3.0.0
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  google_maps_flutter: ^2.11.0
  location: ^8.0.0
  geocoding: ^3.0.0
  youtube_player_flutter: ^9.1.1
  video_player: ^2.9.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.4.0
  uuid: ^4.4.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

agora_rtc_engine:
  git:
    url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
    ref: main



flutter:

  uses-material-design: true

  assets:
    - assets/UST_LOGO_NO_TEXT.png
    - assets/UST_LOGO_WITH_TEXT.png
    - assets/UST_LOGO_NO_TEXT_300.png
    - assets/UST_LOGO_WITH_TEXT_300.png
    - assets/UST-1.jpg
    - assets/ust_logo.png
    - assets/ust_carpark.png
    - assets/user_avatar.png
    - assets/default_user_dp.jpg
