//  assigned dev: janjan
//  this is still a working code, generated by Gemini 2.0 Flash
//  not yet reviewed and tested as of March 18, 2025

import 'package:cloud_firestore/cloud_firestore.dart';

class TrackPastReportsController {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<List<DocumentSnapshot>> viewPastReports(String userId) async {
    try {
      QuerySnapshot reportsSnapshot = await _firestore
          .collection("incidents") // Assuming you are using "incidents" collection
          .where("created_by", isEqualTo: userId)
          .get();

      List<DocumentSnapshot> reports = reportsSnapshot.docs;
      return reports;
    } catch (e) {
      print("Error viewing past reports: $e");
      return []; // Return an empty list on error
    }
  }

  void displayReport(DocumentSnapshot report) {
    try {
      Map<String, dynamic>? data = report.data() as Map<String, dynamic>?;

      if (data != null) {
        String status = data["status"]?.toString() ?? "Unknown";
        Timestamp? createdAt = data["created_at"] as Timestamp?;
        String createdAtString = createdAt != null
            ? createdAt.toDate().toString()
            : "Unknown";

        print("Report #${report.id} - Status: $status - $createdAtString");
      } else {
        print("Report #${report.id} - Data is null");
      }
    } catch (e) {
      print("Error displaying report: $e");
    }
  }
}