// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDepDYLrTjWUHotnkm1t1de4XWPZFcfRY',
    appId: '1:135221844856:web:e323b0c0e20a99dea2068d',
    messagingSenderId: '135221844856',
    projectId: 'tigersafe-test',
    authDomain: 'tigersafe-test.firebaseapp.com',
    storageBucket: 'tigersafe-test.firebasestorage.app',
    measurementId: 'G-RJT36KC5RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZwpplCjcLReEDnwQGOA0Nruw9WqzPzJ8',
    appId: '1:135221844856:android:7f4c416ec57e762da2068d',
    messagingSenderId: '135221844856',
    projectId: 'tigersafe-test',
    storageBucket: 'tigersafe-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pC90vU6foeN1OaUhGP-9jkgv5lp4T8Q',
    appId: '1:135221844856:ios:e1a44466a9252639a2068d',
    messagingSenderId: '135221844856',
    projectId: 'tigersafe-test',
    storageBucket: 'tigersafe-test.firebasestorage.app',
    iosBundleId: 'com.simplesys.se2Tigersafe',
  );
}
